/**
Sifts through data on the roots of unity generated by DataGenerator
Originally written 2017-02-22
*/

import java.util.List;
import java.util.ArrayList;
import java.io.File;
import java.util.Scanner;
import java.io.FileNotFoundException;

public class DataSifter
{

   public static void siftData(String filename)
   {
      int c = 0;
      int totient = 0;
      int maxRoot = 0;
      int multiplier = 0;
      List<Integer[]> loopLengths = new ArrayList<Integer[]>();
      
      //creates the scanner and checks if file can be found
      File textFile = new File(filename);
      Scanner scanner = null;
      try
      {
         scanner = new Scanner(textFile);
      }
      catch (FileNotFoundException e)
      {
         System.out.println("Data file not found.");
         System.exit(0);
      }
      
      //reads the file
      while(scanner.hasNextLine())
      {
         String line = scanner.nextLine();
         String[] values = line.split("c=|; totient=|; max root=|; multiplier="); //parse line
         if (values.length == 5) //ignore poorly formatted lines
         {
            //set variables
            c = Integer.valueOf(values[1]);
            totient = Integer.valueOf(values[2]);
            maxRoot = Integer.valueOf(values[3]);
            multiplier = Integer.valueOf(values[4]);
            
            //get loop lengths
            line = scanner.nextLine();
            values = line.split(": ");
            
            boolean marked = false;

            //BEGIN TESTS
            //sample test
            if (maxRoot != totient && c<100)
               marked = true;
            //END TESTS
            
            //print if marked by a test
            if (marked)
            {
               System.out.println("CHECK c=" + c + "; totient=" + totient + "; maxRoot=" + maxRoot + "; lists: " + line);
            }            
         }
      }
      scanner.close();
   }
   
   
   /** Sifts data */
   public static void main(String[] args)
   {  
      DataSifter.siftData("generated_data.txt");
   }
}